import * as T from './vendor/three.module.js';
export class RacingEffects{
 constructor(parent){this.parent=parent;this.items=[];this.capacity=100;this.object=new T.Object3D();
  const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d'),gr=x.createRadialGradient(32,32,0,32,32,32);gr.addColorStop(0,'rgba(210,219,227,.5)');gr.addColorStop(.4,'rgba(155,172,189,.3)');gr.addColorStop(1,'rgba(128,150,169,0)');x.fillStyle=gr;x.fillRect(0,0,64,64);
  this.smoke=new T.InstancedMesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),transparent:true,depthWrite:false,opacity:.6}),100);this.smoke.frustumCulled=false;
  this.sparks=new T.InstancedMesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial({color:0xffd069}),100);this.sparks.frustumCulled=false;
  this.debris=new T.InstancedMesh(new T.BoxGeometry(1,1,1),new T.MeshStandardMaterial({color:0x252e36,roughness:.65,metalness:.5}),40);this.debris.frustumCulled=false;
  this.jets=new T.InstancedMesh(new T.SphereGeometry(1,8,6),new T.MeshBasicMaterial({color:0x44d9ff,transparent:true,opacity:.58,blending:T.AdditiveBlending,depthWrite:false}),100);this.jets.frustumCulled=false;
  parent.add(this.smoke,this.sparks,this.debris,this.jets);this.hideAll();this.lastSmoke=0;this.trailTime=new WeakMap();
 }
 hideAll(){const o=this.object;o.scale.setScalar(0);o.updateMatrix();for(const m of[this.smoke,this.sparks,this.debris,this.jets]){for(let i=0;i<m.instanceMatrix.count;i++)m.setMatrixAt(i,o.matrix);m.instanceMatrix.needsUpdate=true;}}
 nitroTrail(car,dt){let time=(this.trailTime.get(car)||0)+dt;if(time<.035){this.trailTime.set(car,time);return;}this.trailTime.set(car,0);const direction=new T.Vector3(0,0,-1).applyQuaternion(car.quaternion);for(const s of[-1,1]){const p=new T.Vector3(s*.65,.38,-2.9).applyQuaternion(car.quaternion).add(car.position);this.add(p,direction.clone().multiplyScalar(2.5).add(new T.Vector3(0,.12,0)),.36,'jet',.12);}}
 land(position){for(let i=0;i<12;i++)this.add(position.clone().add(new T.Vector3((Math.random()-.5)*2,.12,(Math.random()-.5)*3)),new T.Vector3((Math.random()-.5)*3,.6,(Math.random()-.5)*3),.5,'smoke',.18);}
 add(p,v,life,type,size){if(this.items.length>=190)this.items.shift();this.items.push({p:p.clone(),v,life,max:life,type,size,rotation:Math.random()*Math.PI});}
 crash(position,forward,strength=1){for(let i=0;i<32;i++)this.add(position.clone().addScaledVector(forward,1.5).add(new T.Vector3(0,.45,0)),new T.Vector3((Math.random()-.5)*13,Math.random()*6,(Math.random()-.5)*13),.3+Math.random()*.6,'spark',.018);for(let i=0;i<10;i++)this.add(position.clone().add(new T.Vector3(0,.6,0)),new T.Vector3((Math.random()-.5)*5,Math.random()*2+1,(Math.random()-.5)*5),1.4+Math.random(),'smoke',.5);for(let i=0;i<8;i++)this.add(position.clone().add(new T.Vector3(0,.5,0)),new T.Vector3((Math.random()-.5)*8,Math.random()*6,(Math.random()-.5)*8),1.5,'debris',.05+Math.random()*.07);}
 update(dt,camera,player,race){if(dt>0){if(race.boosting)this.nitroTrail(player,dt);this.lastSmoke+=dt;if(this.lastSmoke>.07&&((race.drifting&&!race.airborne)||race.health<28)){this.lastSmoke=0;this.add(player.position.clone().add(new T.Vector3((Math.random()-.5)*1.5,.35,0)),new T.Vector3(0,.8,0),.85,'smoke',race.drifting?.25:.45)}}
  const counts={spark:0,smoke:0,debris:0,jet:0},models={spark:this.sparks,smoke:this.smoke,debris:this.debris,jet:this.jets};
  for(let i=this.items.length-1;i>=0;i--){const p=this.items[i];p.life-=dt;if(p.life<=0){this.items.splice(i,1);continue;}p.p.addScaledVector(p.v,dt);if(p.type!=='smoke'&&p.type!=='jet'){p.v.y-=dt*11;if(p.p.y<.05){p.p.y=.05;p.v.y=Math.abs(p.v.y)*.3;p.v.x*=.94;p.v.z*=.94;}}else p.v.multiplyScalar(Math.exp(-dt*.4));const m=models[p.type],index=counts[p.type]++;if(index>=m.instanceMatrix.count)continue;const o=this.object;o.position.copy(p.p);if(p.type==='jet'){o.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),p.v.clone().normalize());const fade=p.life/p.max;o.scale.set(p.size*fade,p.size*fade,.4*fade);}else if(p.type==='smoke'){o.quaternion.copy(camera.quaternion);o.scale.setScalar(p.size*(1+(1-p.life/p.max)*4));}else if(p.type==='spark'){o.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),p.v.clone().normalize());o.scale.set(p.size,p.size,Math.max(.08,p.v.length()*.02));}else{o.rotation.set(p.rotation+p.life*3,p.life*4,0);o.scale.setScalar(p.size);}o.updateMatrix();m.setMatrixAt(index,o.matrix);}
  const o=this.object;o.scale.setScalar(0);o.updateMatrix();for(const [kind,m]of Object.entries(models)){for(let i=Math.min(counts[kind],m.instanceMatrix.count);i<m.instanceMatrix.count;i++)m.setMatrixAt(i,o.matrix);m.instanceMatrix.needsUpdate=true;}
 }
}
