import * as T from './vendor/three.module.js';
import {CARS,DRIVERS,TRACKS,Race,parseSave,purchase,upgrade,upgradeCost,carStats,settleRace,clamp,PARTS,buyPart,usePart} from './core.js?v=9';
import {createCar,createDriver,updateCar,updateDamage,mesh,box,material} from './models.js?v=9';
import {TrackWorld} from './world.js?v=9';
import {createCharacter,animateCharacter,STYLES} from './characters.js?v=9';
import {Cockpit} from './cockpit.js?v=9';
import {RacingEffects} from './effects.js?v=9';
import {resolveVehicleContacts} from './collision.js?v=9';
import {RacingAudio} from './audio.js?v=9';
import {VictoryCelebration} from './podium.js?v=9';
let celebration=null;
const $=id=>document.getElementById(id),keys={},fmt=t=>Math.floor(t/60)+':'+(t%60).toFixed(2).padStart(5,'0');
let raw;try{raw=localStorage.getItem('nitro-rivals-v2')}catch{}const save=parseSave(raw);
let page='landing',previewCar=save.selectedCar,trackIndex=0,world,race,player,opponents=[],cameraMode=0,cruise=false,previousState,driverAsset=null,avatar,showCar,toastTimer,shake=0,gamepadLatch={},particles=[],weather,skids=[],lastSkid=0,elapsedView=0,raceFX,inspectDriver=false,lookDrag=null,renderProgress=0;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.1,2000),showroom=new T.Group(),raceObjects=new T.Group();scene.add(showroom,raceObjects);
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});}catch(e){$('error').hidden=false;$('error').textContent='WebGL is unavailable. Enable hardware acceleration or open this game in Chrome or Edge.';throw e}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,save.settings.quality==='high'?1.5:1));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.outputColorSpace=T.SRGBColorSpace;
const ambient=new T.HemisphereLight(0xe5f5ff,0x475157,2.1),sun=new T.DirectionalLight(0xffe6c4,3.1),rim=new T.DirectionalLight(0xa2eaf1,2);sun.position.set(15,25,10);rim.position.set(-10,12,-8);scene.add(ambient,sun,rim);
const envCanvas=document.createElement('canvas');envCanvas.width=512;envCanvas.height=256;const ec=envCanvas.getContext('2d'),eg=ec.createLinearGradient(0,0,0,256);eg.addColorStop(0,'#303e48');eg.addColorStop(.32,'#a9bfc5');eg.addColorStop(.45,'#506674');eg.addColorStop(.55,'#151f28');eg.addColorStop(1,'#060a0e');ec.fillStyle=eg;ec.fillRect(0,0,512,256);ec.fillStyle='#efffff';ec.fillRect(40,30,20,120);ec.fillRect(280,20,12,90);const studioEnv=new T.CanvasTexture(envCanvas);studioEnv.mapping=T.EquirectangularReflectionMapping;studioEnv.colorSpace=T.SRGBColorSpace;
const floor=mesh(new T.PlaneGeometry(120,120),new T.MeshStandardMaterial({color:0x172129,metalness:.45,roughness:.3}),showroom,0,-.02);floor.rotation.x=-Math.PI/2;const grid=new T.GridHelper(100,40,0x273741,0x1b2933);grid.position.y=-.012;showroom.add(grid);
for(let i=0;i<7;i++){const lightmat=new T.MeshBasicMaterial({color:i%2?0x668b94:0x9ccdbb});box(.035,.015,35,lightmat,showroom,-12+i*4,0,0)}
function persist(){try{localStorage.setItem('nitro-rivals-v2',JSON.stringify(save))}catch{toast('Storage unavailable — progress lasts for this session.')}updateWallet()}
function updateWallet(){$('wallet').textContent=save.coins.toLocaleString();$('ownedCount').textContent=save.owned.length+' / 4';}
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3300)}
function disposeObject(o){o.traverse(c=>{c.geometry?.dispose();if(c.material){const a=Array.isArray(c.material)?c.material:[c.material];a.forEach(m=>{m.map?.dispose();m.dispose()})}});o.parent?.remove(o)}
function refreshDriver(){if(avatar)disposeObject(avatar);avatar=createCharacter(DRIVERS[save.driver]);avatar.position.set(2.3,.025,-.5);avatar.rotation.y=.2;showroom.add(avatar);avatar.visible=page==='garage';$('driverCredit').textContent=DRIVERS[save.driver].name+' / '+STYLES[DRIVERS[save.driver].name].title+' · '+DRIVERS[save.driver].bio;}
function updateShowcar(){if(showCar)disposeObject(showCar);const spec=CARS.find(c=>c.id===previewCar);showCar=createCar(spec,save.paint[previewCar]||spec.color);showroom.add(showCar);showCar.rotation.y=-.35;refreshDriver();}
function showroomCamera(){if(inspectDriver&&avatar){camera.fov=35;const h=STYLES[DRIVERS[save.driver].name].height;camera.position.set(avatar.position.x+.32,1.7*h,avatar.position.z+1.6);camera.lookAt(avatar.position.x,1.48*h,avatar.position.z);camera.updateProjectionMatrix();return;}const small=innerWidth<700;camera.fov=page==='landing'?43:46;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();if(small){camera.position.set(7,4.1,10);camera.lookAt(0,page==='landing'?3.5:1.8,0)}else{camera.position.set(8.1,3.7,10);camera.lookAt(page==='landing'?-2.2:-1.65,.7,0)}}
function setPage(next){page=next;if(next!=='race'){celebration?.dispose();celebration=null;document.body.classList.remove('victory','podium');}if(next!=='race'){inspectDriver=false;document.body.classList.remove('cockpit-view');}clearKeys();$('landing').hidden=next!=='landing';$('garage').hidden=next!=='garage';$('header').hidden=next==='race';$('hud').hidden=next!=='race';$('overlay').hidden=true;$('controls').hidden=true;$('touch').hidden=next!=='race'||!matchMedia('(pointer:coarse)').matches;document.body.classList.toggle('racing',next==='race');$('navHome').classList.toggle('active',next==='landing');$('navGarage').classList.toggle('active',next==='garage');if(next!=='race'){showroom.visible=true;raceObjects.visible=false;if(world)world.group.visible=false;scene.background=new T.Color(0x101922);scene.environment=studioEnv;scene.environmentIntensity=1.3;scene.fog=new T.Fog(0x101922,20,80);ambient.intensity=2;sun.intensity=3.4;rim.intensity=2;camera.fov=45;showroomCamera();avatar.visible=next==='garage';cockpit.setVisible(false);inspectDriver=false;$('boostFX').style.opacity=0;$('crashFX').style.opacity=0;window.scrollTo(0,0);renderGarage()}else{showroom.visible=false;raceObjects.visible=true;world.group.visible=true;}}
function renderGarage(){updateWallet();$('carList').innerHTML='';for(const c of CARS){const b=document.createElement('button');b.className='car-option'+(c.id===previewCar?' active':'');b.innerHTML='<span class="swatch" style="background:'+c.color+'"></span><b>'+c.name+'</b><small>'+(save.owned.includes(c.id)?(save.selectedCar===c.id?'✓ EQUIPPED':'OWNED'):'◈ '+c.price.toLocaleString())+'</small>';b.onclick=()=>{previewCar=c.id;updateShowcar();renderGarage()};$('carList').append(b)}const c=carStats(save,previewCar),owned=save.owned.includes(previewCar),lvl=save.upgrades[previewCar]||0;$('carName').textContent=c.name;$('carTag').textContent=c.tag;$('carDescription').textContent=c.desc;$('carStats').innerHTML='<div>TOP SPEED<b>'+Math.round(c.speed*3.6)+'</b>KM/H</div><div>0–100<b>'+(100/3.6/c.accel+1.1).toFixed(1)+'</b>SECONDS</div><div>HANDLING<b>'+Math.round(c.grip*75)+'</b>RATING</div>';$('buyCar').textContent=owned?(save.selectedCar===previewCar?'✓ EQUIPPED':'EQUIP '+c.name):'UNLOCK · ◈ '+c.price;$('buyCar').disabled=owned?save.selectedCar===previewCar:save.coins<c.price;$('upgradeLevel').textContent='Stage '+lvl+' / 3';$('upgradeCar').textContent=lvl>=3?'MAXED':'◈ '+upgradeCost(save,previewCar)+' UPGRADE';$('upgradeCar').disabled=!owned||lvl>=3||save.coins<upgradeCost(save,previewCar);$('startRace').disabled=!owned;$('startRace').innerHTML=owned?'RACE NOW <span>↗</span>':'UNLOCK CAR TO RACE';$('heroCarName').textContent=c.name;$('heroCarSpeed').textContent=Math.round(c.speed*3.6);$('paints').innerHTML='';for(const color of[c.color,'#dce4e8','#252c34','#df4b39','#bff55c','#a59bea']){const b=document.createElement('button');b.className='paint'+((save.paint[previewCar]||c.color)===color?' active':'');b.style.background=color;b.setAttribute('aria-label','Paint '+color);b.onclick=()=>{save.paint[previewCar]=color;persist();updateShowcar();renderGarage()};$('paints').append(b)}$('driverList').innerHTML='';DRIVERS.forEach((d,i)=>{const b=document.createElement('button');b.textContent=d.name;b.className=i===save.driver?'active':'';b.onclick=()=>{save.driver=i;persist();refreshDriver();renderGarage();if(inspectDriver)showroomCamera()};$('driverList').append(b)});const best=save.best[TRACKS[trackIndex].id+'-'+$('modeSelect').value+'-'+previewCar];$('bestTime').textContent=best?'PERSONAL BEST '+fmt(best):'Set your first personal best. Finish races to bank coins.';renderParts();}
$('buyCar').onclick=()=>{if(purchase(save,previewCar)){persist();renderGarage();toast('Your '+CARS.find(c=>c.id===previewCar).name+' is equipped.')}};$('upgradeCar').onclick=()=>{if(upgrade(save,previewCar)){persist();renderGarage();toast('Performance kit installed. Acceleration, speed, and grip increased.')}};
TRACKS.forEach((t,i)=>{const opt=document.createElement('option');opt.value=i;opt.textContent=t.name;$('trackSelect').append(opt);const b=document.createElement('button');b.className='world-card';const positions=['100% 3%','0% 0%','100% 59%'];b.innerHTML='<div class="landscape" style="background-image:url(concept.png);background-size:310%;background-position:'+positions[i]+'"></div><div class="content"><small>'+t.tag+'</small><h3>'+t.name+'</h3><span class="arrow">↗</span></div>';b.onclick=()=>{trackIndex=i;$('trackSelect').value=i;setPage('garage')};$('worldCards').append(b)});
$('trackSelect').onchange=()=>{trackIndex=Number($('trackSelect').value);renderGarage()};$('modeSelect').onchange=renderGarage;for(const id of['playNow','exploreGarage','navGarage'])$(id).onclick=()=>setPage('garage');for(const id of['navHome','brandHome'])$(id).onclick=e=>{e.preventDefault();setPage('landing')};
const sound=new RacingAudio();function toggleSound(){save.settings.sound=!save.settings.sound;sound.init();sound.enabled=save.settings.sound;$('sound').textContent=save.settings.sound?'♫ ON':'♫ OFF';persist()};$('sound').onclick=toggleSound;$('sound').textContent=save.settings.sound?'♫ ON':'♫ OFF';
addEventListener('pointerdown',()=>sound.init(),{once:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden){sound.silence();sound.ctx?.suspend().catch(()=>{});}else if(sound.ctx)sound.ctx.resume().catch(()=>{});});
$('musicEnabled').checked=save.settings.music;$('musicEnabled').onchange=e=>{save.settings.music=e.target.checked;sound.init();persist();};
function clearRaceObjects(){celebration?.dispose();celebration=null;document.body.classList.remove('victory','podium');for(const child of [...raceObjects.children])disposeObject(child);opponents=[];particles=[];skids=[];weather=null}
function makeWeather(){if(TRACKS[trackIndex].kind==='coast')return;const n=save.settings.quality==='high'?450:160,arr=new Float32Array(n*3);for(let i=0;i<n;i++){arr[i*3]=(Math.random()-.5)*100;arr[i*3+1]=Math.random()*50;arr[i*3+2]=(Math.random()-.5)*100}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(arr,3));weather=new T.Points(geo,new T.PointsMaterial({color:TRACKS[trackIndex].kind==='city'?0x93bed5:0xffffff,size:TRACKS[trackIndex].kind==='city'?.08:.18,transparent:true,opacity:.65}));raceObjects.add(weather)}
function startRace(){if(!save.owned.includes(previewCar))return;save.selectedCar=previewCar;persist();clearRaceObjects();world?.dispose();world=new TrackWorld(scene,TRACKS[trackIndex],save.settings.quality);race=new Race({car:carStats(save,previewCar),trackLength:world.length,grip:TRACKS[trackIndex].grip,mode:$('modeSelect').value,difficulty:$('difficulty').value,assist:save.settings.assist,seed:trackIndex+1,collisionFrame:p=>world.frame(p),ramps:world.ramps});world.createPickups(race.pickups);player=createCar(race.car,save.paint[previewCar]||race.car.color);raceObjects.add(player);raceFX=new RacingEffects(raceObjects);for(const r of race.opponents){const c=r.car,m=createCar(c,DRIVERS[(r.id+save.driver+1)%6].color);raceObjects.add(m);opponents.push(m);world.place(m,r.progress,r.lane)}world.place(player,0);cameraMode=0;cockpit.setVisible(false);lookReset();cruise=false;shake=0;$('cruise').textContent='AUTO THROTTLE: OFF';setPage('race');ambient.intensity=TRACKS[trackIndex].kind==='city'?1.6:2.4;sun.intensity=TRACKS[trackIndex].kind==='city'?.65:3.1;rim.intensity=.8;makeWeather();$('raceLocation').textContent=TRACKS[trackIndex].name;sound.init();for(const r of[race,...race.opponents])r.renderPrev={progress:r.progress,lane:r.lane,yaw:r.yaw,height:r.height,pitch:r.pitch};renderProgress=0;lastSkid=0;cockpit.setCar(race.car,save.paint[previewCar]||race.car.color);updateCamera(1,true);drawHUD();}
$('startRace').onclick=startRace;$('restart').onclick=startRace;$('backGarage').onclick=()=>setPage('garage');
function pause(){if(page!=='race'||!race)return;if(race.status==='paused'){race.status=previousState||'racing';$('overlay').hidden=true;clearKeys();sound.init();return}if(race.status==='finished')return;previousState=race.status;race.status='paused';clearKeys();sound.silence();$('overlayEyebrow').textContent='TAKE A BREATHER';$('overlayTitle').textContent='PIT STOP.';$('overlayText').textContent='Your rivals can wait. Get back out there when you’re ready.';$('resultBreakdown').innerHTML='';$('resume').hidden=false;$('overlay').hidden=false;}
$('pause').onclick=pause;$('resume').onclick=pause;$('cruise').onclick=()=>{cruise=!cruise;$('cruise').textContent='AUTO THROTTLE: '+(cruise?'ON':'OFF')};
let helpPaused=false;function openHelp(){helpPaused=page==='race'&&race.status!=='paused'&&race.status!=='finished';if(helpPaused)pause();$('controls').hidden=false}function closeHelp(){$('controls').hidden=true;if(helpPaused){pause();helpPaused=false}}for(const id of['navControls','raceHelp','pauseControls'])$(id).onclick=openHelp;$('closeControls').onclick=closeHelp;
$('steeringAssist').checked=save.settings.assist;$('cameraShake').checked=save.settings.shake;$('quality').value=save.settings.quality;$('steeringAssist').onchange=e=>{save.settings.assist=e.target.checked;if(race)race.assist=save.settings.assist;persist()};$('cameraShake').onchange=e=>{save.settings.shake=e.target.checked;persist()};$('quality').onchange=e=>{save.settings.quality=e.target.value;renderer.setPixelRatio(Math.min(devicePixelRatio,save.settings.quality==='high'?1.5:1));persist()};
function clearKeys(){for(const k of Object.keys(keys))keys[k]=false}addEventListener('keydown',e=>{if(['SELECT','INPUT'].includes(e.target.tagName))return;if(page==='race'&&['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape'){if(!$('controls').hidden)closeHelp();else pause()}if(e.code==='KeyP')pause();if(e.code==='KeyH')$('controls').hidden?openHelp():closeHelp();if(e.code==='KeyM')toggleSound();if(e.code==='KeyF'){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{})}if(page==='race'){if(e.code==='KeyE')useSpare('repair');if(e.code==='KeyB')useSpare('nitro');if(e.code==='KeyC')changeCamera();if(e.code==='KeyR')respawn();if(e.code==='KeyV')lookReset();if(e.code==='KeyQ'&&!race.rewind())toast('Rewind becomes ready after 3 seconds. Once per race.')}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>{clearKeys();if(page==='race'&&race&&race.status!=='paused')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearKeys();if(page==='race'&&race?.status!=='paused')pause()}});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys[b.dataset.key]=false});
function input(){const gp=Array.from(navigator.getGamepads?.()||[]).find(Boolean);if(gp){for(const [n,act]of[[9,pause],[3,()=>race?.rewind()]]){if(gp.buttons[n]?.pressed&&!gamepadLatch[n])act();gamepadLatch[n]=gp.buttons[n]?.pressed}}return {throttle:!(keys.KeyS||keys.ArrowDown||keys.KeyX||gp?.buttons[6]?.value>.1)&&(cruise||keys.KeyW||keys.ArrowUp||gp?.buttons[7]?.value>.1),reverse:keys.KeyX,brake:keys.KeyS||keys.ArrowDown||gp?.buttons[6]?.value>.1,turn:gp&&Math.abs(gp.axes[0])>.12?gp.axes[0]:(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),left:keys.KeyA||keys.ArrowLeft||gp?.axes[0]<-.18,right:keys.KeyD||keys.ArrowRight||gp?.axes[0]>.18,boost:keys.ShiftLeft||keys.ShiftRight||gp?.buttons[0]?.pressed,drift:keys.Space||gp?.buttons[2]?.pressed}}
function sparks(strength=1){raceFX.crash(player.position,world.frame(race.progress).d,strength);shake=save.settings.shake?.35:0;sound.hit();$('windshield').style.opacity=cameraMode===2?String((100-race.health)/120):'0';}
function effects(dt){for(let i=0;i<opponents.length;i++)if(race.opponents[i].boosting)raceFX.nitroTrail(opponents[i],dt);raceFX.update(dt,camera,player,race);shake=Math.max(0,shake-dt*1.5);$('crashFX').style.opacity=String(shake*1.5);$('boostFX').style.opacity=race.boosting?'1':'0';$('windshield').style.opacity=cameraMode===2?String((100-race.health)/140):'0';if(weather){weather.position.copy(player.position);const attr=weather.geometry.attributes.position;for(let i=0;i<attr.count;i++){attr.array[i*3+1]-=dt*(TRACKS[trackIndex].kind==='city'?22:4);if(attr.array[i*3+1]<0)attr.array[i*3+1]=50}attr.needsUpdate=true;}if(race.drifting&&!race.airborne&&race.time-lastSkid>.13){lastSkid=race.time;const f=world.frame(race.progress-1.5);for(const s of[-1,1]){const m=mesh(new T.PlaneGeometry(.22,1.1),new T.MeshBasicMaterial({color:0x080c0e,transparent:true,opacity:.5,depthWrite:false}),raceObjects);m.position.copy(f.p).addScaledVector(f.n,race.lane+s*.9);m.position.y=.05;m.rotation.x=-Math.PI/2;m.rotation.z=-player.rotation.y;skids.push(m)}while(skids.length>64)disposeObject(skids.shift());}}
function updateCamera(dt,snap=false){
 const f=world.frame(renderProgress),p=player.position;
 const direction=f.d.clone().multiplyScalar(Math.cos(race.yaw)).addScaledVector(f.n,Math.sin(race.yaw));const target=p.clone().addScaledVector(direction,cameraMode===0?-9.7:cameraMode===1?1.9:.16);if(cameraMode===2)target.addScaledVector(f.n,.38);
 target.y=player.position.y+(cameraMode===0?3.45+race.speed*.008:1.55);
 if(save.settings.shake&&shake>0){target.x+=Math.sin(elapsedView*65)*shake*.13;target.y+=Math.cos(elapsedView*55)*shake*.06;}
 camera.position.lerp(target,snap||cameraMode!==0?1:1-Math.exp(-dt*8));
 const look=target.clone().addScaledVector(cameraMode===0?f.d:direction,24);look.y=player.position.y+(cameraMode===0?1.25:1.52);
 const previous=camera.quaternion.clone();camera.lookAt(look);const targetQ=camera.quaternion.clone();
 camera.quaternion.copy(previous).slerp(targetQ,snap||cameraMode!==0?1:1-Math.exp(-dt*9));
 if(cameraMode===2){cockpit.group.position.copy(camera.position);cockpit.group.quaternion.copy(camera.quaternion);
  if(keys.KeyJ)cockpit.targetYaw=clamp(cockpit.targetYaw+dt*.8,-1.25,1.25);if(keys.KeyL)cockpit.targetYaw=clamp(cockpit.targetYaw-dt*.8,-1.25,1.25);
  if(keys.KeyI)cockpit.targetPitch=clamp(cockpit.targetPitch+dt*.6,-.45,.45);if(keys.KeyK)cockpit.targetPitch=clamp(cockpit.targetPitch-dt*.6,-.45,.45);
  cockpit.lookYaw=T.MathUtils.damp(cockpit.lookYaw,cockpit.targetYaw,12,dt);cockpit.lookPitch=T.MathUtils.damp(cockpit.lookPitch,cockpit.targetPitch,12,dt);
  camera.rotateY(cockpit.lookYaw);camera.rotateX(cockpit.lookPitch);cockpit.update(race,dt,world);cockpit.renderMirror(renderer,scene,dt);
 }
 camera.fov=T.MathUtils.damp(camera.fov,cameraMode===2?(race.boosting?70:65):race.boosting?76:62,4,dt);camera.updateProjectionMatrix();player.visible=cameraMode===0;cockpit.setVisible(cameraMode===2);
 $('cameraView').textContent=['C · CHASE','C · HOOD','C · COCKPIT'][cameraMode];$('cockpitHint').hidden=cameraMode!==2;document.body.classList.toggle('cockpit-view',cameraMode===2);
}
function drawMap(){const c=$('map').getContext('2d');c.clearRect(0,0,220,170);const cv=p=>[110+p.x*.39,85+p.z*.39];c.lineWidth=7;c.strokeStyle='#0a1522b0';c.beginPath();for(let i=0;i<=150;i++){const p=cv(world.frame(i/150*world.length).p);i?c.lineTo(...p):c.moveTo(...p)}c.stroke();c.lineWidth=3;c.strokeStyle='#c6d9de88';c.stroke();const st=cv(world.frame(0).p);c.fillStyle='#ffffff';c.fillRect(st[0]-3,st[1]-3,6,6);for(const r of race.opponents){const p=cv(world.frame(r.progress).p);c.fillStyle='#ee9b76';c.beginPath();c.arc(...p,3,0,Math.PI*2);c.fill()}const p=cv(world.frame(race.progress).p);c.fillStyle='#c6f65b';c.beginPath();c.arc(...p,4.5,0,Math.PI*2);c.fill()}
function drawHUD(){$('position').innerHTML=race.mode==='time'?'SOLO':race.rank+'<span> / 6</span>';$('lap').innerHTML=Math.max(1,Math.min(race.laps,Math.floor(race.progress/race.length)+1))+'<span> / '+race.laps+'</span>';$('timer').textContent=fmt(race.time);$('speed').textContent=Math.round(Math.abs(race.speed)*3.6);$('gear').textContent=race.reversing?'GEAR R':'GEAR '+Math.min(6,1+Math.floor(race.speed/12));$('nitroText').textContent=Math.round(race.nitro)+'%';$('nitroBar').style.width=race.nitro+'%';$('heatBar').style.width=race.heat+'%';$('nitroHint').textContent=race.overheated?'OVERHEATED · COOLING':race.boosting?'NITRO ENGAGED':race.drifting?'DRIFTING · RECHARGING':'HOLD SHIFT TO BOOST';$('healthText').textContent=Math.round(race.health)+'%';$('damageText').textContent=Math.round(100-race.health)+'%';$('repairState').textContent=race.status==='recovering'?'CREW RECOVERY · '+Math.ceil(race.rescue)+'s':race.health<35?'CRITICAL · REPAIR OR RESPAWN':race.health<100?(save.inventory.repair?'REPAIR KIT: +35% CONDITION':'NO KITS · ROAD REPAIR OR RESPAWN'):'CAR READY';$('repairCar').textContent='E · REPAIR ('+save.inventory.repair+')';$('refillNitro').textContent='B · REFILL ('+save.inventory.nitro+')';$('repairCar').disabled=race.status!=='racing'||race.health>=100||!save.inventory.repair;$('refillNitro').disabled=race.status!=='racing'||race.nitro>=100||!save.inventory.nitro;$('respawn').disabled=!['racing','recovering'].includes(race.status);$('healthBar').style.width=race.health+'%';$('healthBar').style.background=race.health<35?'#ff735e':'#c6f65b';$('raceCoins').textContent=race.coins;$('driftScore').textContent='DRIFT '+Math.floor(race.drift)+(race.combo>1?' · ×'+(1+Math.min(3,race.combo/3)).toFixed(1):'');$('draftStatus').textContent=race.airborne?'AIRTIME '+race.airTime.toFixed(1)+'s · '+Math.round(race.jumpDistance)+'m':race.draft?'SLIPSTREAM · BOOST RECHARGING':'';$('rewindStatus').textContent=race.rewindUsed?'SECOND CHANCE USED':'Q · SECOND CHANCE READY';$('raceMessage').textContent=race.status==='countdown'?String(Math.ceil(race.countdown)):race.status==='recovering'?'RECOVERING '+Math.ceil(race.rescue):race.eventTime>0?race.event:'';const rows=[{progress:race.progress,name:DRIVERS[save.driver].name+' · YOU',you:true,health:race.health,finish:race.finishTime},...race.opponents.map(r=>({progress:r.progress,name:DRIVERS[(r.id+save.driver+1)%6].name,health:r.health,finish:r.finish}))].sort((a,b)=>a.finish!=null&&b.finish!=null?a.finish-b.finish:a.finish!=null?-1:b.finish!=null?1:b.progress-a.progress);$('standings').innerHTML=rows.map((r,i)=>'<div class="'+(r.you?'you':'')+'"><span>'+String(i+1).padStart(2,'0')+'</span><span>'+r.name+'</span><small>'+Math.round(100-r.health)+'% DMG</small></div>').join('');drawMap();}
function finish(){const reward=settleRace(save,race,TRACKS[trackIndex].id);if(!reward)return;persist();$('overlayEyebrow').textContent=reward.best?'NEW PERSONAL BEST':'THE FINISH LINE';$('overlayTitle').textContent=race.mode==='time'?'TIME ATTACK.':race.rank===1?'VICTORY.':'RACE COMPLETE.';$('overlayText').textContent=(race.mode==='time'?'Solo run':race.rank+' / 6 finish')+' · '+fmt(race.time)+' · '+race.crashes+' impacts · '+race.jumps+' jumps';$('resultBreakdown').innerHTML='<div><span>Finish reward</span><b>◈ '+reward.base+'</b></div><div><span>Pickups & overtakes</span><b>◈ '+reward.collected+'</b></div><div><span>Drift bonus</span><b>◈ '+reward.driftBonus+'</b></div><div><span>Clean race bonus</span><b>◈ '+reward.clean+'</b></div><div class="total"><span>BANKED</span><b>◈ '+reward.reward+'</b></div>';if(race.mode!=='time'){const order=[{driver:DRIVERS[save.driver],progress:race.progress,finish:race.finishTime,color:save.paint[previewCar]||race.car.color,you:true},...race.opponents.map(r=>({driver:DRIVERS[(r.id+save.driver+1)%6],progress:r.progress,finish:r.finish,color:DRIVERS[(r.id+save.driver+1)%6].color,you:false}))].sort((a,b)=>a.finish!=null&&b.finish!=null?a.finish-b.finish:a.finish!=null?-1:b.finish!=null?1:b.progress-a.progress);celebration=new VictoryCelebration(scene,race.car,order.slice(0,3));world.group.visible=false;raceObjects.visible=false;cockpit.setVisible(false);document.body.classList.remove('cockpit-view');document.body.classList.add('podium');document.body.classList.toggle('victory',race.rank===1);scene.background=new T.Color(0x101922);scene.fog=new T.Fog(0x101922,25,65);scene.environment=studioEnv;ambient.intensity=2.7;sun.intensity=3.4;rim.intensity=2;celebration.update(0,camera);$('overlayEyebrow').textContent='NITRO RIVALS CHAMPION';$('winnerName').textContent=order[0].driver.name.toUpperCase();$('winnerPlaces').textContent=order.slice(0,3).map((r,i)=>(i+1)+'. '+r.driver.name).join(' · ');$('resultBreakdown').insertAdjacentHTML('afterbegin','<div class="podium-names"><span>TOP THREE</span><b>'+order.slice(0,3).map((r,i)=>(i+1)+'. '+r.driver.name).join(' / ')+'</b></div>');if(race.rank===1)sound.victory();else sound.coin();} $('resume').hidden=true;$('overlay').hidden=false;$('touch').hidden=true;clearKeys();$('boostFX').style.opacity=0;$('crashFX').style.opacity=0;$('windshield').style.opacity=0;}
let last=performance.now(),acc=0,hudTick=0;
function animate(now){
 const dt=Math.min((now-last)/1000,.1);last=now;elapsedView+=dt;
 if(page==='race'&&race){
  const active=!['paused','finished'].includes(race.status),controls=input();
  if(active){acc+=dt;while(acc>=1/60){
   for(const r of[race,...race.opponents])r.renderPrev={progress:r.progress,lane:r.lane,yaw:r.yaw,height:r.height,pitch:r.pitch};
   race.step(1/60,controls,p=>world.curvature(p));
   for(const event of race.events){if(event.type==='crash')sparks(event.strength);if(event.type==='coin')sound.coin();if(event.type==='jump')sound.jump();if(event.type==='landing'){raceFX.land(player.position);sound.land();}if(event.type==='botCrash'){const bot=race.opponents[event.id];if(bot)raceFX.crash(world.frame(bot.progress).p.clone().addScaledVector(world.frame(bot.progress).n,bot.lane),world.frame(bot.progress).d,event.strength);}if(event.type==='respawn'||event.type==='rewind'){race.renderPrev={progress:race.progress,lane:race.lane,yaw:race.yaw,height:race.height,pitch:race.pitch};updateCamera(1,true);}}
   acc-=1/60;
  }}else acc=0;
  const alpha=active?acc/(1/60):1;
  const visual=[race,...race.opponents].map(r=>{const p=r.renderPrev||r;return {...r,progress:T.MathUtils.lerp(p.progress,r.progress,alpha),lane:T.MathUtils.lerp(p.lane,r.lane,alpha),yaw:T.MathUtils.lerp(p.yaw,r.yaw,alpha),height:T.MathUtils.lerp(p.height??0,r.height,alpha),pitch:T.MathUtils.lerp(p.pitch??0,r.pitch,alpha)};});
  resolveVehicleContacts(visual,race.length,p=>world.frame(p));
  renderProgress=visual[0].progress;
  [player,...opponents].forEach((m,i)=>{const v=visual[i],r=i===0?race:race.opponents[i-1];world.place(m,v.progress,v.lane,.02+v.height);m.rotation.y-=v.yaw;m.rotation.x=v.pitch;const groundShadow=m.userData.shadow;if(groundShadow){const inverse=m.quaternion.clone().invert();groundShadow.position.set(0,.025-v.height,0).applyQuaternion(inverse);groundShadow.quaternion.copy(inverse).multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),-Math.PI/2));groundShadow.material.opacity=Math.max(.15,1-v.height*.18);}updateCar(m,r.speed,r.steer,r.drifting,r.boosting,i===0?(controls.brake||controls.reverse):false,race.time,active?dt:0);});
  if(active){world.animatePickups(race.pickups,race.progress,elapsedView);effects(dt);updateCamera(dt);}
  hudTick+=dt;if(hudTick>.1){drawHUD();updateDamage(player,race.health);race.opponents.forEach((r,i)=>updateDamage(opponents[i],r.health));hudTick=0;}
  if(race.status==='finished'){finish();celebration?.update(dt,camera);}
 }else{showCar.rotation.y=-.35+Math.sin(elapsedView*.18)*.14;animateCharacter(avatar,elapsedView);acc=0;animateShowroom(elapsedView);}
 sound.update(race,{page,enabled:save.settings.sound,music:save.settings.music,track:trackIndex,hidden:document.hidden});renderer.render(scene,camera);requestAnimationFrame(animate);
}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(page!=='race')showroomCamera()}addEventListener('resize',resize);

const cockpit=new Cockpit();scene.add(cockpit.group);
function lookReset(){cockpit.targetYaw=0;cockpit.targetPitch=0;cockpit.lookYaw=0;cockpit.lookPitch=0;}
function changeCamera(){if(race?.status==='finished')return;cameraMode=(cameraMode+1)%3;lookReset();if(race)updateCamera(1,true);}
function respawn(){if(!race||!['racing','recovering'].includes(race.status))return;race.resetCar();if(race){race.renderPrev={progress:race.progress,lane:race.lane,yaw:race.yaw,height:race.height,pitch:race.pitch};renderProgress=race.progress;world.place(player,race.progress,race.lane);updateCamera(1,true);}clearKeys();}
$('respawn').onclick=respawn;$('cameraView').onclick=changeCamera;$('centerLook').onclick=lookReset;
$('inspectDriver').onclick=()=>{inspectDriver=!inspectDriver;$('inspectDriver').textContent=inspectDriver?'BACK TO CAR':'INSPECT DRIVER';showroomCamera();};
$('game').addEventListener('pointerdown',e=>{if(page==='race'&&cameraMode===2){lookDrag={x:e.clientX,y:e.clientY};$('game').setPointerCapture(e.pointerId);}});
$('game').addEventListener('pointermove',e=>{if(!lookDrag||cameraMode!==2)return;cockpit.targetYaw=clamp(cockpit.targetYaw-(e.clientX-lookDrag.x)*.004,-1.25,1.25);cockpit.targetPitch=clamp(cockpit.targetPitch-(e.clientY-lookDrag.y)*.003,-.45,.45);lookDrag={x:e.clientX,y:e.clientY};});
$('game').addEventListener('pointerup',()=>lookDrag=null);$('game').addEventListener('pointercancel',()=>lookDrag=null);
// Illuminated architecture and moving light bars behind the showroom.
const cityBackdrop=new T.Group();showroom.add(cityBackdrop);
for(let i=0;i<25;i++){const x=-30+i*2.4,h=2+(i*13%9);box(1.6,h,1.6,material(i%2?0x142535:0x1d3441,.78),cityBackdrop,x,h/2,-21-(i%3)*3);for(let k=0;k<h;k+=1.2)box(1.5,.05,.015,new T.MeshBasicMaterial({color:i%3?0x3b848b:0x85ac8a}),cityBackdrop,x,k+.5,-20.16-(i%3)*3);}
const lightSweep=box(.13,.015,40,new T.MeshBasicMaterial({color:0xb9e680}),showroom,0,.013,0);
function animateShowroom(time){lightSweep.position.x=Math.sin(time*.19)*13;rim.intensity=1.7+Math.sin(time*.45)*.25;}
updateShowcar();renderGarage();setPage('landing');$('loadState').hidden=true;requestAnimationFrame(animate);

function buildDriverCards(){
 DRIVERS.forEach((d,index)=>{
  const b=document.createElement('button');b.className='driver-card';
  b.innerHTML='<img alt="'+d.name+' 3D character portrait"><b>'+d.name+'</b><small>'+d.call+' / '+STYLES[d.name].title.toUpperCase()+'</small>';
  b.onclick=()=>{save.driver=index;persist();refreshDriver();setPage('garage');inspectDriver=true;showroomCamera();$('inspectDriver').textContent='BACK TO CAR';};
  $('driverCards').append(b);
 });
 const target=new T.WebGLRenderTarget(384,384);target.texture.colorSpace=T.SRGBColorSpace;
 let index=0;
 function portrait(){
  if(index>=DRIVERS.length){target.dispose();return;}
  const mini=new T.Scene();mini.background=new T.Color(0x172837);mini.environment=studioEnv;
  mini.add(new T.HemisphereLight(0xf6f1e2,0x3b4a5a,2.3));const key=new T.DirectionalLight(0xffe0c3,3);key.position.set(2,4,4);mini.add(key);
  const fill=new T.DirectionalLight(0x7bdae7,1.2);fill.position.set(-3,1,2);mini.add(fill);
  const model=createCharacter(DRIVERS[index]);mini.add(model);const cam=new T.PerspectiveCamera(29,1,.1,10);
  cam.position.set(.19,1.69*STYLES[DRIVERS[index].name].height,1.4);cam.lookAt(0,1.5*STYLES[DRIVERS[index].name].height,0);
  renderer.setRenderTarget(target);renderer.render(mini,cam);const pixels=new Uint8Array(384*384*4);renderer.readRenderTargetPixels(target,0,0,384,384,pixels);renderer.setRenderTarget(null);
  const canvas=document.createElement('canvas');canvas.width=canvas.height=384;const x=canvas.getContext('2d'),im=x.createImageData(384,384);
  for(let row=0;row<384;row++)im.data.set(pixels.subarray(row*384*4,(row+1)*384*4),(383-row)*384*4);
  x.putImageData(im,0,0);$('driverCards').children[index].querySelector('img').src=canvas.toDataURL('image/png');
  disposeObject(model);index++;setTimeout(portrait,80);
 }
 setTimeout(portrait,150);
}
buildDriverCards();





function renderParts(){
 const owned=save.owned.includes(previewCar);$('partsList').innerHTML='';
 for(const p of PARTS){const installed=save.parts[previewCar]?.includes(p.id),row=document.createElement('article');row.className='part-item';
 row.innerHTML='<span class="part-symbol">'+p.icon+'</span><div><b>'+p.name+'</b><small>'+p.desc+'</small><em>'+(p.kind==='stock'?'IN BAG: '+save.inventory[p.id]:installed?'INSTALLED':'FOR '+CARS.find(c=>c.id===previewCar).name)+'</em></div>';
 const b=document.createElement('button');b.textContent=installed?'INSTALLED':'◈ '+p.price;b.disabled=installed||save.coins<p.price||p.kind==='installed'&&!owned;
 b.onclick=()=>{if(buyPart(save,p.id,previewCar)){persist();renderGarage();toast(p.name+(p.kind==='stock'?' added to your bag.':' installed. Bots match your upgraded car.'));}};row.append(b);$('partsList').append(row);
 }
}
function useSpare(id){if(usePart(save,race,id)){persist();drawHUD();updateDamage(player,race.health);sound.coin();}else toast(id==='repair'?'Use a repair kit when your car is damaged. Buy kits in the parts shop.':'Use a canister when nitro is below 100%. Buy refills in the parts shop.');}
$('repairCar').onclick=()=>useSpare('repair');$('refillNitro').onclick=()=>useSpare('nitro');
