import * as T from './vendor/three.module.js';
import {mesh,box,material} from './models.js?v=9';
const TAU=Math.PI*2;
function texture(kind){const c=document.createElement('canvas');c.width=kind==='road'?256:128;c.height=kind==='road'?256:256;const x=c.getContext('2d');if(kind==='road'){x.fillStyle='#343940';x.fillRect(0,0,256,256);let seed=312;for(let i=0;i<22000;i++){seed=(seed*1664525+1013904223)>>>0;const p=seed%256;seed=(seed*1664525+1013904223)>>>0;const q=seed%256;x.fillStyle=i%2?'#ffffff0a':'#00000020';x.fillRect(p,q,1,1)}}else{x.fillStyle='#172637';x.fillRect(0,0,128,256);for(let y=4;y<256;y+=12)for(let z=5;z<128;z+=12){x.fillStyle=(y+z)%5===0?'#183147':(y*z)%7<3?'#e8c293':'#76a7b9';x.fillRect(z,y,5,6)}}const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;return tex}
export class TrackWorld{
 constructor(scene,theme,quality='high'){this.group=new T.Group();scene.add(this.group);this.scene=scene;this.theme=theme;this.batches=new Map();this.pickups=[];this.effects=[];this.quality=quality;const points=[];for(let i=0;i<20;i++){const a=i/20*TAU,r=1+.12*Math.sin(3*a+(theme.kind==='canyon'?1:0))+.05*Math.cos(5*a);points.push(new T.Vector3(Math.sin(a)*theme.rx*r,0,Math.cos(a)*theme.rz*r))}this.curve=new T.CatmullRomCurve3(points,true,'catmullrom',.5);this.length=this.curve.getLength();this.samples=Array.from({length:1001},(_,i)=>this.frameExact(i/1000));this.setupSky();this.buildGround();this.buildTrack();this.buildRamps();this.buildScenery();this.flush();}
 frameExact(t){t=((t%1)+1)%1;const p=this.curve.getPointAt(t),d=this.curve.getTangentAt(t).normalize(),n=new T.Vector3(-d.z,0,d.x);return {p,d,n}}
 frame(progress){const a=(((progress/this.length)%1+1)%1)*1000,i=Math.floor(a),u=a-i;const f=this.samples[i],b=this.samples[i+1];return {p:f.p.clone().lerp(b.p,u),d:f.d.clone().lerp(b.d,u).normalize(),n:f.n.clone().lerp(b.n,u).normalize()}}
 curvature(progress){const a=this.frame(progress).d,b=this.frame(progress+5).d;return Math.atan2(a.x*b.z-a.z*b.x,a.dot(b))/5}
 place(obj,progress,lane=0,y=.02){const f=this.frame(progress);obj.position.copy(f.p).addScaledVector(f.n,lane);obj.position.y=y;obj.rotation.y=Math.atan2(f.d.x,f.d.z);return f}
 addBox(w,h,d,color,x,y,z,rotation=0,emissive=false){const key=color+'-'+emissive;let batch=this.batches.get(key);if(!batch){batch={mat:new T.MeshStandardMaterial({color,roughness:.6,metalness:.15,emissive:emissive?color:0,emissiveIntensity:emissive?1.6:0}),items:[]};this.batches.set(key,batch)}batch.items.push({x,y,z,w,h,d,rotation})}
 flush(){const tmp=new T.Object3D();for(const b of this.batches.values()){const m=new T.InstancedMesh(new T.BoxGeometry(1,1,1),b.mat,b.items.length);b.items.forEach((p,i)=>{tmp.position.set(p.x,p.y,p.z);tmp.rotation.set(0,p.rotation,0);tmp.scale.set(p.w,p.h,p.d);tmp.updateMatrix();m.setMatrixAt(i,tmp.matrix)});m.receiveShadow=true;this.group.add(m)}this.batches.clear()}
 setupSky(){const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d'),gradient=ctx.createLinearGradient(0,0,0,256);gradient.addColorStop(0,'#'+this.theme.sky.toString(16).padStart(6,'0'));gradient.addColorStop(.52,'#'+this.theme.horizon.toString(16).padStart(6,'0'));gradient.addColorStop(.58,'#b7bab9');gradient.addColorStop(1,'#313746');ctx.fillStyle=gradient;ctx.fillRect(0,0,512,256);const env=new T.CanvasTexture(c);env.mapping=T.EquirectangularReflectionMapping;env.colorSpace=T.SRGBColorSpace;this.env=env;this.scene.background=env;this.scene.environment=env;this.scene.environmentIntensity=this.theme.kind==='city'?.8:1.2;this.scene.fog=new T.Fog(this.theme.horizon,this.theme.kind==='city'?240:420,1400);}
 buildGround(){const plane=mesh(new T.PlaneGeometry(3000,3000),material(this.theme.ground,.95,0),this.group,0,-.09);plane.rotation.x=-Math.PI/2;if(this.theme.kind==='coast'){const water=mesh(new T.PlaneGeometry(1500,2000,20,20),new T.MeshPhysicalMaterial({color:0x207e9d,metalness:.45,roughness:.28,clearcoat:1}),this.group,-900,-.13,0);water.rotation.x=-Math.PI/2;for(let i=0;i<35;i++)this.addBox(160+i%5*20,.02,.2,0x79bac4,-570-i%5*90,-.1,-900+i*55);for(let i=0;i<7;i++){const x=-380-i*58,z=-400+i*110;this.addBox(8,2,20,0xebf1ef,x,.8,z,.4);this.addBox(.15,18,.15,0xdbe8ef,x,9,z);const sail=mesh(new T.ConeGeometry(6,15,3),material(0xffffff),this.group,x,10,z);sail.scale.z=.03}}}
 buildTrack(){const roadTex=texture('road');roadTex.repeat.set(1,1);const pos=[],uv=[],indices=[];for(let i=0;i<=640;i++){const {p,n}=this.frameExact(i/640);for(const s of[-1,1]){const q=p.clone().addScaledVector(n,s*10);pos.push(q.x,.025,q.z);uv.push(s===-1?0:2,i*this.length/640/12)}if(i<640){const k=i*2;indices.push(k,k+1,k+2,k+1,k+3,k+2)}}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(pos,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setIndex(indices);geo.computeVertexNormals();mesh(geo,new T.MeshStandardMaterial({map:roadTex,roughness:this.theme.kind==='city'?.42:.91,metalness:this.theme.kind==='city'?.32:0,side:T.DoubleSide}),this.group);
 for(let i=0;i<260;i++){const f=this.frameExact(i/260),ang=Math.atan2(f.d.x,f.d.z);for(const s of[-1,1]){const at=f.p.clone().addScaledVector(f.n,s*10.15);this.addBox(.65,.13,this.length/260+.1,i%2?0xf0efde:0xd15a4c,at.x,.1,at.z,ang);const rail=f.p.clone().addScaledVector(f.n,s*11);this.addBox(.2,.5,this.length/260+.2,this.theme.kind==='city'?0x547287:0xa5afb4,rail.x,.7,rail.z,ang);if(i%3===0)this.addBox(.2,1,.2,0x647580,rail.x,.5,rail.z,ang)}if(i%2===0)this.addBox(.13,.02,3.6,0xe9dfcb,f.p.x,.046,f.p.z,ang)}
 for(let i=0;i<32;i++){const f=this.frameExact(i/32),at=f.p.clone().addScaledVector(f.n,13);this.addBox(.17,8,.17,0x5c6870,at.x,4,at.z);this.addBox(3.5,.15,.55,0xd9edf0,at.x+f.n.x*-1.5,8,at.z+f.n.z*-1.5,Math.atan2(f.d.x,f.d.z),true);if(this.theme.kind==='city'&&i%4===0){const light=new T.PointLight(0x4bc9e3,35,28,2);light.position.set(at.x,7,at.z);this.group.add(light)}}
 const start=new T.Group();this.place(start,0);this.group.add(start);const dark=material(0x111a23,.5),light=material(0xe9efe7,.5);for(const s of[-1,1])box(.6,7,.6,dark,start,s*10.6,3.5);box(22,1.3,.65,dark,start,0,7);const c=document.createElement('canvas');c.width=1024;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#121b23';ctx.fillRect(0,0,1024,96);ctx.fillStyle='#c7fc59';ctx.font='bold italic 64px Arial';ctx.textAlign='center';ctx.fillText('N I T R O   R I V A L S',512,70);const banner=new T.Mesh(new T.PlaneGeometry(19,1.8),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),side:T.DoubleSide}));banner.position.set(0,7,.35);start.add(banner);for(let i=0;i<20;i++)for(let row=0;row<2;row++)box(1,.035,1,(i+row)%2?dark:light,start,i-9.5,.04,row-.5);
 // A lit tunnel on the city circuit; track-aligned ribs follow the curve.
 if(this.theme.kind==='city')for(let i=0;i<20;i++){const f=this.frame(this.length*.36+i*4);const a=Math.atan2(f.d.x,f.d.z);for(const s of[-1,1]){const p=f.p.clone().addScaledVector(f.n,s*12);this.addBox(.7,8,4.1,0x293d4b,p.x,4,p.z,a)}this.addBox(24,.45,4.1,0x1d2b3b,f.p.x,8,f.p.z,a);if(i%2===0)this.addBox(23,.08,.18,i%4?0x23e5e2:0xda6dcd,f.p.x,7.7,f.p.z,a,true)}
 }
 buildScenery(){const kind=this.theme.kind;const treeMat=material(kind==='alpine'?0x35594d:0x487249,.95),trunkMat=material(0x695345,.95);const treeGeo=new T.ConeGeometry(1,1,7),trunkGeo=new T.CylinderGeometry(.3,.4,1,6);const trees=[];for(let i=0;i<120;i++){const t=i/120,f=this.frameExact(t),side=i%2?1:-1,dist=18+(i*13%65),p=f.p.clone().addScaledVector(f.n,side*dist);if(kind==='coast'&&p.x<-240)continue;trees.push(p)}
 if(kind==='coast'||kind==='alpine'){const trunks=new T.InstancedMesh(trunkGeo,trunkMat,trees.length),leaves=new T.InstancedMesh(treeGeo,treeMat,trees.length*(kind==='coast'?5:3));const obj=new T.Object3D();let n=0;trees.forEach((p,i)=>{const h=kind==='coast'?10+i%4:9+i%6;obj.position.set(p.x,h/2,p.z);obj.rotation.set(0,0,kind==='coast'?.13:0);obj.scale.set(1,h,1);obj.updateMatrix();trunks.setMatrixAt(i,obj.matrix);for(let k=0;k<(kind==='coast'?5:3);k++){if(kind==='coast'){const a=k/5*TAU;obj.position.set(p.x+Math.sin(a)*2.5,h-.1,p.z+Math.cos(a)*2.5);obj.rotation.set(Math.sin(a)*1.1,a,Math.cos(a)*1.1);obj.scale.set(1.1,7,1.2)}else{obj.position.set(p.x,h*.5+k*2,p.z);obj.rotation.set(0,i,0);obj.scale.set(3.8-k*.7,6,3.8-k*.7)}obj.updateMatrix();leaves.setMatrixAt(n++,obj.matrix)}});this.group.add(trunks,leaves);}
 if(kind==='city'){const win=texture('windows'),mat=new T.MeshStandardMaterial({map:win,emissiveMap:win,emissive:0xc9b9a1,emissiveIntensity:.55,roughness:.6});for(let i=0;i<100;i++){const f=this.frameExact(i/100),side=i%2?1:-1,p=f.p.clone().addScaledVector(f.n,side*(28+i%7*13)),h=12+(i*23%90);const b=mesh(new T.BoxGeometry(12+i%4*4,h,12+i%3*5),mat,this.group,p.x,h/2,p.z);b.rotation.y=i*.7;if(i%4===0)this.addBox(15,.3,15,i%8?0x28bdb8:0xa8478b,p.x,h*.85,p.z,0,true)}}
 if(kind==='canyon'||kind==='alpine'){for(let i=0;i<40;i++){const a=i/40*TAU,dist=340+i%5*80,h=(kind==='alpine'?100:55)+(i*17%110);const m=mesh(new T.ConeGeometry(60+i%7*13,h,kind==='alpine'?6:5,2),material(kind==='alpine'?(i%2?0x8b9ea7:0x6b8290):(i%2?0xb07550:0x985438),1,0),this.group,Math.sin(a)*dist,h/2-10,Math.cos(a)*dist);m.rotation.y=i;if(kind==='alpine'){const cap=mesh(new T.ConeGeometry((60+i%7*13)*.38,h*.38,6),material(0xeef4f6,1),this.group,m.position.x,h*.81-10,m.position.z);cap.rotation.y=i}}}
 if(kind==='coast'){for(let i=0;i<23;i++){const f=this.frameExact(.12+i*.025),p=f.p.clone().addScaledVector(f.n,40+i%4*12);if(p.x<-220)continue;const h=6+i%4*3;this.addBox(11,h,9,0xe5d5be,p.x,h/2,p.z);this.addBox(12,.6,10,0xc48d6e,p.x,h,p.z);for(let k=0;k<3;k++)this.addBox(1.6,2,.1,0x3d6577,p.x-3+k*3,h*.65,p.z+4.56)}}
 // Trackside tire stacks, sponsor boards, and chevrons make corners readable.
 for(let i=0;i<18;i++){const f=this.frameExact(i/18),p=f.p.clone().addScaledVector(f.n,16),a=Math.atan2(f.d.x,f.d.z);this.addBox(5,1.7,.25,i%2?0x202d37:0xd3d5c8,p.x,1.1,p.z,a);this.addBox(2,.3,.28,this.theme.accent,p.x,1.1,p.z,a,true)}
 }
 buildRamps(){
 this.ramps=[.18,.49,.77].map((fraction,i)=>({id:i,progress:this.length*fraction,lane:[0,-4,4][i],length:12,width:6,height:1.5}));
 const steel=material(0x273b46,.65,.45),orange=new T.MeshStandardMaterial({color:0xffa534,emissive:0xd65b11,emissiveIntensity:.35});
 for(const a of this.ramps){const g=new T.Group();this.place(g,a.progress+a.length/2,a.lane,0);this.group.add(g);
  const vertices=[-3,.03,-6,3,.03,-6,-3,1.53,6,3,1.53,6,-3,.03,6,3,.03,6],geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geo.setIndex([0,2,1,1,2,3,0,4,2,1,3,5,2,4,3,3,4,5]);geo.computeVertexNormals();mesh(geo,new T.MeshStandardMaterial({color:0x354b5a,roughness:.65,metalness:.5,side:T.DoubleSide}),g);
  for(const s of[-1,1]){const edge=box(.13,.07,12.1,orange,g,s*2.88,.79);edge.rotation.x=-Math.atan2(1.5,12);}
  for(let k=0;k<4;k++){const z=-3+k*2;for(const s of[-1,1]){const arrow=box(1.5,.035,.25,orange,g,s*.62,.03+(z+6)/12*1.5+.04,z);arrow.rotation.y=s*.55;arrow.rotation.x=-Math.atan2(1.5,12);}}
  const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle='#101923';x.fillRect(0,0,512,160);x.fillStyle='#ffb84c';x.font='bold 52px Arial';x.textAlign='center';x.fillText('JUMP ↑',256,68);x.font='22px Arial';x.fillStyle='#ffffff';x.fillText('HIT THE RAMP AT SPEED',256,117);
  const sign=mesh(new T.PlaneGeometry(4.3,1.3),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),side:T.DoubleSide}),g,0,4,5.5);sign.rotation.y=Math.PI;for(const s of[-1,1])box(.09,4.6,.09,steel,g,s*2.9,2.3,5.5);
 }
 }
 createPickups(items){const materials={coin:new T.MeshStandardMaterial({color:0xffcc46,metalness:.8,roughness:.23,emissive:0xc47b0c,emissiveIntensity:.2}),nitro:new T.MeshStandardMaterial({color:0x39e5ff,emissive:0x0ba3bc,emissiveIntensity:1}),repair:new T.MeshStandardMaterial({color:0x7aff9d,emissive:0x23994c,emissiveIntensity:.7})};items.forEach(p=>{const m=mesh(p.type==='coin'?new T.TorusGeometry(.42,.13,8,16):new T.OctahedronGeometry(.58),materials[p.type],this.group);this.place(m,p.progress,p.lane,1.3);this.pickups.push(m)})}
 animatePickups(items,progress,time){const lap=Math.floor(progress/this.length);this.pickups.forEach((m,i)=>{m.visible=!items[i].taken.includes(lap);m.rotation.y=time*2;m.position.y=1.25+Math.sin(time*3+i)*.13})}
 dispose(){this.group.traverse(o=>{o.geometry?.dispose();if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.map?.dispose();m.dispose()})}});this.scene.remove(this.group);this.env.dispose()}
}
