import assert from 'node:assert/strict';
import {Race,CARS,TRACKS,DRIVERS,freshSave,parseSave,purchase,upgrade,carStats,settleRace,driveVehicle,vehicleState} from '../core.js';
assert.equal(TRACKS.length,3);assert.equal(DRIVERS.length,6);
const s=freshSave();assert(!purchase(s,'spectre'));assert.equal(s.coins,500);assert(upgrade(s,'pulse'));assert.equal(s.coins,150);assert(!upgrade(s,'pulse'));assert.equal(parseSave('{').coins,500);assert.equal(parseSave(JSON.stringify({...s,coins:-9,owned:['bad']})).coins,0);
for(const track of TRACKS)for(const mode of ['sprint','circuit','time']){const r=new Race({car:carStats(s,'pulse'),trackLength:1100,grip:track.grip,mode});for(let i=0;i<30000&&r.status!=='finished';i++)r.step(1/60,{throttle:true,boost:i%500<120});assert.equal(r.status,'finished',track.id+mode);const before=s.coins,reward=settleRace(s,r,track.id);assert(reward.reward>0);assert.equal(s.coins,before+reward.reward);assert.equal(settleRace(s,r,track.id),null);assert.equal(s.coins,before+reward.reward)}
const r=new Race({car:CARS[0],trackLength:1000,mode:'time'});r.status='racing';r.speed=45;r.crash();assert(r.health<100);assert(r.speed<45);const hp=r.health;r.crash();assert.equal(r.health,hp);r.cooldown=0;r.health=1;r.crash();assert.equal(r.status,'recovering');for(let i=0;i<200;i++)r.step(1/60,{});assert.equal(r.status,'racing');assert(r.health>0);for(let i=0;i<250;i++)r.step(1/60,{throttle:true});const progress=r.progress;assert(r.rewind());assert(r.progress<progress);assert(!r.rewind());r.status='paused';const time=r.time;r.step(1,{});assert.equal(r.time,time);
const b=new Race({car:CARS[0],trackLength:5000,mode:'time'});b.status='racing';b.nitro=100;for(let i=0;i<300;i++)b.step(1/60,{throttle:true,boost:true});assert(b.nitro<100);assert(!Number.isNaN(b.speed));
assert(purchase(s,'blaze'));assert(s.owned.includes('blaze'));assert.equal(parseSave(JSON.stringify(s)).selectedCar,'blaze');
console.log('PASS: 3 locations × 3 complete race modes, 6 drivers, purchases, upgrades, saves, collision cooldown, recovery, rewind, nitro, pause, and exactly-once rewards.');
