import assert from 'node:assert/strict';
import {Race,CARS,DRIVERS,vehicleState,driveVehicle,carStats,freshSave} from '../core.js';
assert.equal(DRIVERS.filter(d=>d.gender==='female').length,3);
assert.equal(DRIVERS.filter(d=>d.gender==='male').length,3);
assert(DRIVERS.some(d=>d.name==='Anjan'));assert(DRIVERS.some(d=>d.name==='Jaggu'));
assert(!DRIVERS.some(d=>['Freya','Zuri'].includes(d.name)));
const v=vehicleState();for(let i=0;i<240;i++)driveVehicle(v,1/60,{throttle:1,boost:1},0,CARS[0],1);
const boosted=v.speed;driveVehicle(v,1/60,{throttle:1},0,CARS[0],1);
assert(Math.abs(v.speed-boosted)<1,'boost release must not snap speed');
for(let i=0;i<6000;i++)driveVehicle(v,1/60,{throttle:1,turn:Math.sin(i/100)},.005,CARS[0],1);
assert(Number.isFinite(v.speed)&&Number.isFinite(v.lane)&&Number.isFinite(v.yaw));
const save=freshSave();save.upgrades.pulse=3;
const r=new Race({car:carStats(save,'pulse'),trackLength:5000});
assert.equal(r.opponents.length,5);for(const b of r.opponents)assert.deepEqual(b.car,r.car);
r.status='racing';r.progress=100;r.speed=40;r.opponents.forEach((b,i)=>{b.progress=-100-i*10});
const b=r.opponents[0];b.progress=103;b.lane=0;b.speed=35;
r.step(1/60,{throttle:1});assert(r.health<100&&b.health<100);assert(Math.abs(r.health-b.health)<1);
r.health=0;r.status='recovering';r.rescue=2;r.resetCar();assert.equal(r.status,'racing');assert.equal(r.rescue,0);assert(r.health>=50);
r.status='paused';const states=[r,...r.opponents].map(b=>[b.progress,b.speed,b.health]);r.step(1,{});
assert.deepEqual([r,...r.opponents].map(b=>[b.progress,b.speed,b.health]),states);
console.log('PASS: smooth boost release, finite steering, 3 women/3 men, renamed drivers, equal bot stats, symmetric contact, respawn, and pause.');
